name: 'Renovate Docker Builder'
description: 'Action for building and testing renovate docker images'
inputs:
  command:
    description: 'Command to execute'
    required: true
  image:
    description: 'docker image to operate on'
    required: true
  tags:
    description: 'semicolon sepearted list of docker image tags to operate on'
    required: false
    default: 'latest'
  dry-run:
    description: 'do not publish anything'
    required: false
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
