name: 'Renovate Docker Builder'
description: 'Action for building and testing renovate docker images'
inputs:
  command:
    description: 'Command to execute'
    required: true
  image:
    description: 'docker image to operate on'
    required: false
    default:
  tags:
    description: 'semicolon sepearted list of docker image tags to operate on'
    required: false
    default: 'latest'
  dry-run:
    description: 'do not publish anything'
    required: false
    default: false
  token:
    description: 'Github PAT, commands which needs a token will fail build without'
    required: false
    default:
  config:
    description: 'docker-builder: config file'
    required: false
    default: builder.json
  last-only:
    description: 'docker-builder: build only latest version'
    required: false
    default: false
  build-only:
    description: 'docker-builder: no docker push'
    required: false
    default: false
  build-args:
    description: 'docker-builder: additional docker build args'
    required: false
    default:
  tag-suffix:
    description: 'docker-builder: additional docker tag suffix to append'
    required: false
    default:

runs:
  using: 'node12'
  main: 'dist/index.js'
