# no packages yet
packages: []

allowBuilds:
  better-sqlite3: false
  core-js-pure: false
  dtrace-provider: false
  protobufjs: false
  re2: false
  unrs-resolver: false

# need to publish workspace root with correct version
includeWorkspaceRoot: true

# in line with https://github.com/containerbase/.github/blob/main/default.json,
# all non-Renovate or non-Containerbase packages should only be installed after
# 3 days
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@renovatebot/*'
  - '@containerbase/*'

overrides:
  dtrace-provider: '-'
  vite: 8.0.10
  vitest: 4.1.5

patchedDependencies:
  '@baszalmstra/rattler': patches/@baszalmstra__rattler.patch
  re2: patches/re2.patch

strictPeerDependencies: true
