# no packages yet
packages: []

allowBuilds:
  better-sqlite3: false
  protobufjs: false
  re2: false

# need to publish workspace root with correct version
includeWorkspaceRoot: true

overrides:
  '@yarnpkg/core@4.5.0>tar': 7.5.13
  vite: $vite
  vitest: $vitest

patchedDependencies:
  '@baszalmstra/rattler': patches/@baszalmstra__rattler.patch
  re2: patches/re2.patch

strictPeerDependencies: true
