# no packages yet
packages: []

# need to publish workspace root with correct version
includeWorkspaceRoot: true

strictPeerDependencies: true
strictDepBuilds: true

neverBuiltDependencies:
  - dtrace-provider

ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - esbuild
  - moment
  - mv
  - protobufjs
  - re2
  - safe-json-stringify
  - unrs-resolver
