# no packages yet
packages: []

# need to publish workspace root with correct version
includeWorkspaceRoot: true

strictPeerDependencies: true
strictDepBuilds: true

onlyBuiltDependencies:
  - re2

ignoredBuiltDependencies:
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - esbuild
  - protobufjs
  - unrs-resolver
