name: 'Setup Node.js'
description: 'Deprecated! Setup Node and install dependencies using cache'
inputs:
  save-cache:
    description: 'Save cache when needed'
    required: false
    default: 'false'

runs:
  using: 'composite'

  steps:
    - shell: bash
      run: echo "::warning title=Deprecation notice::Use setup action instead of setup-node"

    - uses: ./setup
      with:
        checkout: false
        save-cache: ${{ inputs.save-cache }}
