name: 'Publish releases'
description: 'Publishs the github releases as json file to github pages'
inputs:
  token:
    description: 'GitHub token'
    required: true
  dry-run:
    description: 'do not publish anything'
    required: false
    default: 'false'

outputs:
  page_url:
    description: 'URL of the published GitHub Pages'
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: 'composite'

  steps:
    # Workaround
    # - https://github.com/actions/runner/issues/2101
    # - https://github.com/orgs/community/discussions/26245#discussioncomment-15601440
    - name: Copy actions
      run: |
        mkdir -p ${{ github.workspace }}/.actions
        ln -sf ${{ github.action_path }}/.. ${{ github.workspace }}/.actions/internal-tools
      shell: bash
    - name: Generate release list
      uses: ./.actions/internal-tools
      with:
        command: release-list
        token: ${{ inputs.token }}

    - name: Upload GitHub Pages artifact
      if: inputs.dry-run == 'false'
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0

    - name: Deploy to GitHub Pages
      if: inputs.dry-run == 'false'
      id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
