name: 'Setup'
description: 'Setup runner'
inputs:
  checkout:
    description: 'Checkout repository'
    required: false
    default: 'true'
  node:
    description: 'Setup node and pnpm'
    required: false
    default: 'true'
  node-version:
    description: 'Override node version from .node-version file'
    required: false
    default: ''
  pnpm-cache:
    description: 'Paths to pnpm node_modules to cache'
    required: false
    default: 'node_modules'
  save-cache:
    description: 'Save cache when needed'
    required: false
    default: 'false'
  apt-proxy:
    description: 'Setup apt proxy'
    required: false
    default: 'false'

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      if: inputs.checkout == 'true'
      with:
        show-progress: false

    - shell: bash
      if: inputs.node == 'true'
      run: |
        if [ -n "${{ inputs.node-version }}" ]; then
          echo 'CACHE_KEY=node_modules-${{ inputs.node-version }}-${{
            hashFiles('package.json', 'pnpm-lock.yaml')
          }}' >> "$GITHUB_ENV"
        else
          echo 'CACHE_KEY=node_modules-${{
            hashFiles('.node-version', 'package.json', 'pnpm-lock.yaml')
          }}' >> "$GITHUB_ENV"
        fi

    - uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      if: inputs.node == 'true'
      id: node-modules-restore
      with:
        path: ${{ inputs.pnpm-cache }}
        key: ${{ env.CACHE_KEY }}
        enableCrossOsArchive: true

    - shell: bash
      if: inputs.node == 'true'
      run: |
        echo 'CACHE_HIT=${{
          (steps.node-modules-restore.outputs.cache-hit == 'true') && 'true' || ''
        }}' >> "$GITHUB_ENV"

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      if: inputs.node == 'true'
      # TODO: Use standalone version?
      # with:
      #   standalone: true

    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      if: inputs.node == 'true'
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && '.node-version' || '' }}
        cache: ${{ env.CACHE_HIT != 'true' && 'pnpm' || '' }}

    - if: inputs.node == 'true' && env.CACHE_HIT != 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
      env:
        # Other environment variables
        HUSKY: '0' # By default do not run HUSKY install

    - if: inputs.node == 'true' && inputs.save-cache == 'true' && env.CACHE_HIT != 'true'
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: ${{ inputs.pnpm-cache }}
        key: ${{ env.CACHE_KEY }}
        enableCrossOsArchive: true

    - if: inputs.apt-proxy == 'true'
      shell: bash
      run: |
        echo "::group::Preparing squid-deb-proxy"
        set -e
        sudo apt-get -qq update
        sudo apt-get install -y squid-deb-proxy
        echo "ppa.launchpad.net" | sudo tee -a /etc/squid-deb-proxy/mirror-dstdomain.acl.d/containerbase.acl
        sudo systemctl reload squid-deb-proxy
        echo "::endgroup::"
