name: publish

on:
  repository_dispatch:
    types: [publish]

env:
  VERSION: v0
  NODE_VERSION: 12
  YARN_CACHE_KEY: v0
  YARN_CACHE_FOLDER: .cache/yarn
  # https://github.com/chalk/supports-color/issues/106
  FORCE_COLOR: true

jobs:
  publish:
    runs-on: ubuntu-latest

    # tests shouldn't need more than 15 min
    timeout-minutes: 15

    steps:
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Init platform
        id: init
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
          git config --global user.email 'bot@renovateapp.com'
          git config --global user.name  'Renovate Bot'
          yarn config set version-git-tag false

      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
          ref: 'release'
          persist-credentials: false

      - name: Cache Yarn packages
        id: yarn_cache_packages
        uses: actions/cache@v2.1.2
        with:
          path: ${{ env.YARN_CACHE_FOLDER }}
          key: ${{ env.YARN_CACHE_KEY }}-${{ runner.os }}-yarn_cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ env.YARN_CACHE_KEY }}-${{ runner.os }}-yarn_cache-

      - name: Cache node_modules
        uses: actions/cache@v2.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-yarn-

      - run: yarn install --frozen-lockfile

      - run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
